# Generated by Django 3.0.4 on 2020-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
